Ciphey/Ciphey

- .gitmodules
> ITS NOT DONE YET!!!

- .gitignore
- ciphey/Decryptor/Encoding/bases.py
- ciphey/Decryptor/Encoding/encodingParent.py
- ciphey/Decryptor/Hash/hashBuster.py
- ciphey/Decryptor/Hash/hashParent.py
- ciphey/Decryptor/basicEncryption/basic_parent.py
- ciphey/__main__.py
- docs/ciphers.rst
- pyproject.toml
- tests/enciphey.py
- tests/generate_tests.py
> PLS BEFORE MY 4G DIES

- ciphey/Decryptor/Encoding/encodingParent.py
- ciphey/Decryptor/Encoding/octal.py
> Add in octal 

- tests/test_main.py
- help menu prints on no argument inputs
- fixing CI
> fixingImportActions

- ciphey/ciphey.py
* Removed offline mode from arguments list, as it's not used﻿
> removed useless arguments

- .all-contributorsrc
> Fix invalid JSON

- ciphey/basemods/Crackers/caesar.py
- ciphey/basemods/Crackers/vigenere.py
Casting for p-values was just non-existent, so I have done some stuff to it
> Fixed casting for p values

- README.md
- translations/de/CODE_OF_CONDUCT.de.md
- translations/de/CONTRIBUTING.md
- translations/de/README.md
- translations/id/CODE_OF_CONDUCT.id.md
- translations/id/README.md
Add a german translation for the README.md, CONTRIBUTING.md and CODE_OF_CONDUCT.md
> Add german docs

- tests/test_main.py
Fixed Base62 and Base91 tests. Now all tests but one successfully pass with pytest.
> Fix Base62 and Base91 tests

- tests/test_main.py
Added a Base58 Ripple test. Successfully passes with pytest.
> Add Base58 Ripple test

- .github/ISSUE_TEMPLATE/bug_report.md
- ciphey/basemods/Checkers/entropy.py
Updated the bug report with giant flaring alerts maybe they'll read it now and fill it out
> Maybe they'll read the bug report now.

- README.md
> Updated docs links to wiki

- ciphey/basemods/Decoders/__init__.py
- ciphey/basemods/Decoders/decimal.py
- tests/test_main.py
This adds decimal decoding to Ciphey. Also has support for multiple delimiters, and I added a test.
> Add decimal

- README.md
> updated GitHub username

- README.md
> remove codacy badge

- ciphey/basemods/Decoders/morse.py
Morse wasn't working. Now it do
> Fixed morse

- README.md
- translations/hu/CODE_OF_CONDUCT.md
- translations/hu/CONTRIBUTING.md
- translations/hu/README.md
Readme, Code of Conduct and Contributing documents translated to Hungarian.
Everything has been kept as close to the original meaning as possible.
> Hungarian Translation

- ciphey/basemods/Decoders/base65536.py
Adds ability to decode Base65536 into the files. It isn't added to init.py yet.
> Add Base65536

- README.md
- translations/pt-br/CODE_OF_CONDUCT.md
- translations/pt-br/CONTRIBUTING.md
- translations/pt-br/README.md
Added translation to brazillian portuguese for the documents: README.md, CONTRIBUTING.md and CODE_OF_CONDUCT.md
> Pt br translate

- README.md
- translations/pt-br/README.md
Link in README to the portuguese version was wrong
> Option to go to portuguese version was with the wrong link

- README.md
> Fixed Broken Link on RU translation

- ciphey/basemods/Crackers/__init__.py
- ciphey/basemods/Crackers/ascii_shift.py
- tests/test_main.py
Adds ASCII shift cracker to Ciphey. It uses ASCII characters 1-127. I also added a test.
> Add ASCII shift

- ciphey/basemods/Decoders/galactic.py
- tests/test_main.py
- also modify corresponding test case
- and move comments describing code above it
> Fix issue #262 - 'x' surrounded by letters in Galactic Alphabet Decoder

- ciphey/ciphey.py
so i wasn't able to exit ciphey chika was hawing the same problem
and even tho it was saying it stopped it really didn't here are screenshots of ps
the only thing that could stop it at that point was SIGKILL so i added keyboard interupt exception
> fix can't exit ciphey

- ciphey/ciphey.py
Revert changes from #526 to fix issues.
> Revert changes

- README.md
Removes broken badge from README
> Broken badge

- ciphey/basemods/Searchers/ausearch.py
- tests/test_main.py
> Revert "Bee fix ausearch"

- ciphey/basemods/Checkers/human.py
- ciphey/basemods/Checkers/what.py
> Made Cipheys output more friendly and fixed the what bug

- ciphey/mathsHelper.py
> Fix typo in mathsHelper.py

- ciphey/iface/_modules.py
> Remove unnecessary newline

- ciphey/basemods/Checkers/what.py
- tests/test_click.py
`pywhat` did not respect greppable so it printed during that mode.
This fixes that and adds a new test to make sure it doesn't happen again.
> Add click tests & fix greppable bug with `pywhat`

- ciphey/basemods/Searchers/ausearch.py
I have fixed AuSearch, and replaced it with an asymptotically faster algorithm.
A brief history of this for interested parties:
- The first working version of AuSearch made a best-effort guess at the best ordering, and then iterated through it, transposing all pairs of elements until it didn't get any faster, then estimating again, and so on until a stationary point was reached. This is theoretically O(n!), but behaved slightly more like O(2^n) due to the estimation step.
- I was working on an experimental version of AuSearch that used dynamic programming methods to find the best path, which would make it a more well-behaved O(2^n). This had no estimation step, and so was slower in some cases, hence why it wasn't pushed. 
For those unfamiliar with DP (and I'm still a bit shaky on it …
> Reworked AuSearch
